<?xml version='1.0'?>

<robot name="udacity_bot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find udacity_bot)/urdf/udacity_bot.gazebo" />

  <xacro:property name="wheel_length" value="0.05" />
  <xacro:property name="wheel_radius" value="0.1" />
  <xacro:property name="wheel_mass" value="5" />
  <xacro:property name="wheel_inertia" value="0.1" />

  <xacro:property name="chassis_width" value="0.2" />
  <xacro:property name="chassis_length" value="0.3" />
  <xacro:property name="chassis_depth" value="0.1" />
  <xacro:property name="chassis_mass" value="15" />
  <xacro:property name="chassis_inertia" value="0.1" />

  <xacro:property name="chassis_x_offset" value="${chassis_length/2 + 0.05}" />
  <xacro:property name="wheel_x_offset" value="${chassis_x_offset + chassis_length/2 - wheel_radius}" />
  <xacro:property name="wheel_y_offset" value="${(chassis_width + 0.1) / 2}" />

  <xacro:property name="steer_angle_limit" value="0.95" />
  <xacro:property name="steer_velocity" value="1" />


  <link name="robot_footprint"></link>

  <joint name="robot_footprint_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="robot_footprint"/>
    <child link="back_chassis" />
  </joint>

  <!-- back chassis -->
  <link name='back_chassis'>
    <inertial>
      <mass value="${chassis_mass}"/>
      <origin xyz="-${chassis_x_offset} 0 0" rpy=" 0 0 0"/>
      <inertia
          ixx="${chassis_inertia}" ixy="0" ixz="0"
          iyy="${chassis_inertia}" iyz="0"
          izz="${chassis_inertia}" />
    </inertial>
    <collision name='collision'>
      <origin xyz="-${chassis_x_offset} 0 0" rpy=" 0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_depth}"/>
      </geometry>
    </collision>
    <visual name='chassis_visual'>
      <origin xyz="-${chassis_x_offset} 0 0" rpy=" 0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_depth}"/>
      </geometry>
    </visual>
    <visual name='back_chassis_link_visual'>
      <origin xyz="-0.025 0 0" rpy=" 0 0 0"/>
      <geometry>
        <box size=".05 .01 .05"/>
      </geometry>
    </visual>
    <visual name='chassis_pin_visual'>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <geometry>
        <cylinder length="0.06" radius="0.025"/>
      </geometry>
    </visual>
  </link>


  <link name="left_wheel">
    <inertial>
      <mass value="${wheel_mass}"/>
      <origin xyz="0 0 0" rpy=" 0 1.5707 1.5707"/>
      <inertia
          ixx="${wheel_inertia}" ixy="0" ixz="0"
          iyy="${wheel_inertia}" iyz="0"
          izz="${wheel_inertia}" />
    </inertial>
    <collision name="left_wheel_collision">
      <origin xyz="0 0 0" rpy=" 0 1.5707 1.5707"/>
      <geometry>
        <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <visual name="left_wheel_visual">
      <origin xyz="0 0 0" rpy=" 0 1.5707 1.5707"/>
      <geometry>
        <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
      </geometry>
    </visual>
  </link>
  <joint type="continuous" name="left_wheel_hinge">
    <origin xyz="-${wheel_x_offset}  ${wheel_y_offset} 0" rpy="0 0 0"/>
    <child link="left_wheel"/>
    <parent link="back_chassis"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="10000" velocity="1000"/>
    <joint_properties damping="1.0" friction="1.0"/>
  </joint>


  <link name="right_wheel">
    <inertial>
      <mass value="${wheel_mass}"/>
      <origin xyz="0.0 0 0" rpy=" 0 1.5707 1.5707"/>
      <inertia
          ixx="${wheel_inertia}" ixy="0" ixz="0"
          iyy="${wheel_inertia}" iyz="0"
          izz="${wheel_inertia}" />
    </inertial>
    <collision name="right_wheel_collision">
      <origin xyz="0 0 0" rpy=" 0 1.5707 1.5707"/>
      <geometry>
        <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <visual name="right_wheel_visual">
      <origin xyz="0 0 0" rpy=" 0 1.5707 1.5707"/>
      <geometry>
        <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
      </geometry>
    </visual>
  </link>
  <joint type="continuous" name="right_wheel_hinge">
    <origin xyz="-${wheel_x_offset} -${wheel_y_offset} 0" rpy="0 0 0"/>
    <child link="right_wheel"/>
    <parent link="back_chassis"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="10000" velocity="1000"/>
    <joint_properties damping="1.0" friction="1.0"/>
  </joint>


  <!-- front chassis -->
  <joint type="revolute" name="chassis_hinge">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <child link="front_chassis"/>
    <parent link="back_chassis"/>
    <axis xyz="0 0 1" rpy="0 0 0"/>
    <limit effort="10000" lower="-${steer_angle_limit}" upper="${steer_angle_limit}" velocity="${steer_velocity}"/>
    <joint_properties damping="1.0" friction="1.0"/>
  </joint>
  <link name='front_chassis'>
    <inertial>
      <mass value="${chassis_mass}"/>
      <origin xyz="${chassis_x_offset} 0 0" rpy=" 0 0 0"/>
      <inertia
          ixx="${chassis_inertia}" ixy="0" ixz="0"
          iyy="${chassis_inertia}" iyz="0"
          izz="${chassis_inertia}" />
    </inertial>
    <collision name='collision'>
      <origin xyz="${chassis_x_offset} 0 0" rpy=" 0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_depth}"/>
      </geometry>
    </collision>
    <visual name='chassis_visual'>
      <origin xyz="${chassis_x_offset} 0 0" rpy=" 0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_depth}"/>
      </geometry>
    </visual>
    <visual name='front_chassis_link_visual'>
      <origin xyz="0.025 0 0" rpy=" 0 0 0"/>
      <geometry>
        <box size=".05 .01 .05"/>
      </geometry>
    </visual>
  </link>


  <link name="left_front_wheel">
    <inertial>
      <mass value="${wheel_mass}"/>
      <origin xyz="0.0 0 0" rpy=" 0 1.5707 1.5707"/>
      <inertia
          ixx="${wheel_inertia}" ixy="0" ixz="0"
          iyy="${wheel_inertia}" iyz="0"
          izz="${wheel_inertia}" />
    </inertial>
    <collision name="collision">
      <origin xyz="0 0 0" rpy=" 0 1.5707 1.5707"/>
      <geometry>
        <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <visual name="visual">
      <origin xyz="0 0 0" rpy=" 0 1.5707 1.5707"/>
      <geometry>
        <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
      </geometry>
    </visual>
  </link>
  <joint type="continuous" name="left_front_wheel_hinge">
    <origin xyz="${wheel_x_offset} ${wheel_y_offset} 0" rpy="0 0 0"/>
    <child link="left_front_wheel"/>
    <parent link="front_chassis"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="10000" velocity="1000"/>
    <joint_properties damping="1.0" friction="1.0"/>
  </joint>


  <link name="right_front_wheel">
    <inertial>
      <mass value="${wheel_mass}"/>
      <origin xyz="0.0 0 0" rpy=" 0 1.5707 1.5707"/>
      <inertia
          ixx="${wheel_inertia}" ixy="0" ixz="0"
          iyy="${wheel_inertia}" iyz="0"
          izz="${wheel_inertia}" />
    </inertial>
    <collision name="collision">
      <origin xyz="0 0 0" rpy=" 0 1.5707 1.5707"/>
      <geometry>
        <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <visual name="visual">
      <origin xyz="0 0 0" rpy=" 0 1.5707 1.5707"/>
      <geometry>
        <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
      </geometry>
    </visual>
  </link>
  <joint type="continuous" name="right_front_wheel_hinge">
    <origin xyz="${wheel_x_offset} -${wheel_y_offset} 0" rpy="0 0 0"/>
    <child link="right_front_wheel"/>
    <parent link="front_chassis"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="10000" velocity="1000"/>
    <joint_properties damping="1.0" friction="1.0"/>
  </joint>


  <!-- camera -->
  <link name='camera'>
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0.0 0 0" rpy=" 0 0 0"/>
      <inertia
          ixx="1e-6" ixy="0" ixz="0"
          iyy="1e-6" iyz="0"
          izz="1e-6"/>
    </inertial>
    <collision name='camera_collision'>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <geometry>
        <box size=".05 .05 .05"/>
      </geometry>
    </collision>
    <visual name='camera_visual'>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <geometry>
        <box size=".05 .05 .05"/>
      </geometry>
    </visual>
  </link>
  <joint type="fixed" name="camera_joint">
    <origin xyz="${chassis_x_offset + chassis_length/2} 0 0" rpy="0 0 0"/>
    <child link="camera"/>
    <parent link="front_chassis"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="10000" velocity="1000"/>
    <joint_properties damping="1.0" friction="1.0"/>
  </joint>

  <!-- laser -->
  <link name='hokuyo'>
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <inertia
          ixx="1e-6" ixy="0" ixz="0"
          iyy="1e-6" iyz="0"
          izz="1e-6" />
    </inertial>
    <collision name='hokuyo_collision'>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <geometry>
        <box size=".1 .1 .1"/>
      </geometry>
    </collision>
    <visual name='hokuyo_visual'>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <geometry>
        <mesh filename="package://udacity_bot/meshes/hokuyo.dae"/>
      </geometry>
    </visual>
  </link>
  <joint type="fixed" name="hokuyo_joint">
    <origin xyz="${chassis_x_offset} 0 ${wheel_radius + 0.01}" rpy="0 0 0"/>
    <child link="hokuyo"/>
    <parent link="front_chassis"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="10000" velocity="1000"/>
    <joint_properties damping="1.0" friction="1.0"/>
  </joint>

</robot>
