TrajectoryPlannerROS:
  max_vel_x: 0.5
  min_vel_x: 0.1
  max_vel_theta: 0.5
  min_in_place_vel_theta: 0.1

  acc_lim_theta: 1.0
  acc_lim_x: 1.5
  acc_lim_y: 1.5

  meter_scoring: true

  holonomic_robot: false
